swagger: '2.0'
info:
  version: 1.0.0
  title: Recipe Book API
  description: Recipe Book API documentation using swagger.
  contact:
    email: mattia.buffetti@gmail.com
# noinspection YamlSchema
servers:
  - url: https://recipebook-lemon.vercel.app
    description: Production server
  - url: http://localhost:3000
    description: Development server
basePath: /api
paths:
  # noinspection YamlSchema
  $ref: ./paths/index.yaml
definitions:
  # noinspection YamlSchema
  $ref: ./definitions/index.yaml
